# Generated by Django 4.1.1 on 2022-10-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Clasificacion',
            new_name='Calificacion',
        ),
    ]
